src/account/urls.py
from django.urls import path

from account import views

app_name = "account"

urlpatterns = [
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
]

src/donation/api/urls.py
from rest_framework import routers

from donation.api.views import DonationViewSet

# from django.urls import path


app_name = "donations-api"

router = routers.SimpleRouter()
router.register(r"", DonationViewSet, basename="donation")
urlpatterns = router.urls

src/donation/urls.py
from django.urls import path
from django.views.generic import TemplateView

from donation.views import DonationView

app_name = "donations"

urlpatterns = [
    path(
        "boo/", TemplateView.as_view(template_name="donate_cancel.html"), name="cancel"
    ),
    path(
        "thanks/",
        TemplateView.as_view(template_name="donate_complete.html"),
        name="complete",
    ),
    path("start/", DonationView.as_view(), name="start"),
    path("cost/", TemplateView.as_view(template_name="cost.html"), name="cost"),
]

src/donation/models.py
from math import floor

from django.conf import settings
from django.db import models

# https://django-paypal.readthedocs.io/en/stable/standard/ipn.html


class Donation(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="donations", on_delete=models.PROTECT
    )
    amount = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=25, null=True, blank=True)
    comment = models.TextField(
        null=True,
        blank=True,
        default=None,
        help_text="Tell me why you're donating today",
    )
    moderated_comment = models.TextField(
        null=True,
        blank=True,
        default=None,
        help_text="This will be displayed to the world",
    )
    private = models.BooleanField(
        null=True, default=False, help_text="Do not show my name alongside the donation"
    )
    confirmed = models.BooleanField(null=True, default=False)


class Campaign(models.Model):
    # TODO: add constraint to ensure that campaigns do not overlap
    start = models.DateTimeField()
    end = models.DateTimeField()
    target = models.IntegerField()

    @property
    def donations(self):
        return Donation.objects.filter(
            created__lte=self.end, created__gt=self.start, confirmed=True
        )

    @property
    def collected(self):
        return self.donations.aggregate(models.Sum("amount"))["amount__sum"] or 0

    @property
    def percent_complete(self):
        return max(2, min(99, floor(self.collected / self.target * 100)))

src/donation/forms.py
# from django import forms

# from donation.models import Donation


# class DonationForm(forms.ModelForm):
#     class Meta:
#         model = Donation
#         fields = ('comment', 'private')

src/donation/api/views.py
import bleach
from django_filters import rest_framework as filters
from rest_framework import mixins, viewsets
from rest_framework.permissions import IsAdminUser, IsAuthenticated

from donation.api.serializers import (
    DonationDisplaySerializer,
    DonationSerializer,
)
from donation.models import Donation


class CreateListRetrieveViewSet(
    mixins.CreateModelMixin,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    viewsets.GenericViewSet,
):
    pass


class DonationFilterSet(filters.FilterSet):
    class Meta:
        model = Donation
        fields = {
            "id": ["lt", "gt", "exact"],
            "created": [
                "lt",
                "gt",
                "year",
                "month",
                "day",
                "week",
                "week_day",
                "quarter",
                "hour",
            ],
        }


class DonationViewSet(CreateListRetrieveViewSet):
    queryset = Donation.objects.filter(confirmed=True, amount__gt=0).order_by(
        "-created"
    )
    model = Donation
    serializer_class = DonationDisplaySerializer
    lookup_url_kwarg = "donation_pk"
    permission_classes = [IsAdminUser]
    permission_classes_by_action = {
        "create": [IsAuthenticated],
    }
    serializer_class_by_action = {
        "create": DonationSerializer,
    }
    filterset_class = DonationFilterSet

    def perform_create(self, serializer):
        # print(self.request.user)
        instance = serializer.save(user=self.request.user)
        instance.moderated_comment = bleach.clean(instance.comment)
        instance.save()

    def get_permissions(self):
        try:
            return [
                permission()
                for permission in self.permission_classes_by_action[self.action]
            ]
        except KeyError:
            return [permission() for permission in self.permission_classes]

    def get_serializer_class(self):
        try:
            return self.serializer_class_by_action[self.action]
        except KeyError:
            return self.serializer_class

src/donation/views.py
from django.views.generic import TemplateView

from donation.models import Donation


class DonationView(TemplateView):
    template_name = "donate.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        donations = Donation.objects.filter(confirmed=True).order_by("-created")[:25]
        context.update({"donations": donations})
        return context

src/donation/templates/cost.html
{% extends "site_base.html" %}

{% block head_title %}Site Cost Breakdown{% endblock %}

{% block content %}
<h1>Cost Analysis</h1>
<p>The $1300 per year figure on the front page is based on the following real and forecast data.</p>
<p>This site is delivered by a <a href="https://kubernetes.io/">Kubernetes Cluster</a> hosted by <a href="https://aws.amazon.com/">AWS</a>. The static files (e.g. the videos) are served from an <a href="https://aws.amazon.com/s3/">S3 bucket</a>. Where possible I purchase reservations to cover the resource usage within AWS; this helps to minimize the price. For simplicity I use AWS services where possible so that all resources can be managed from a single place; as such small items cost slightly more than they might when purchased from a service dedicated to that offering. For example, domain registration (paying for and claiming the <tt>tutorpaul.com</tt> address) might only cost $9 per year when purchased from the cheapest source; registration through <a href="https://aws.amazon.com/route53/">AWS Route 53</a> costs $12 per year.</p>

<p>Savvy readers will note that this site is quite small for a Kubernetes cluster; they're right. I use Kubernetes because I like it, and I use the excess capacity on the cluster for other projects. This site is the long pole in the tent&mdash;the cluster primarily exists to deliver <tt>tutorpaul.com</tt>. The costs in the table below that represent potentially shared resources are marked.</p>

<table style="border: 1px solid #000;">
    <thead>
        <tr>
            <th>Provider</th>
            <th>Service</th>
            <th>Terms</th>
            <th>Cost</th>
            <th>Annual Price</th>
            <th>Notes</th>
        <tr>
    </thead>
    <tbody  style="border-top: 1px solid #000">
        <tr>
            <td>AWS</td>
            <td>Route 53</td>
            <td>Annual + Monthly</td>
            <td>$12 + $1/month</td>
            <td align="right">$24.00</td>
            <td><small>Domain registration + DNS for <tt>tutorpaul.com</tt></small></td>
        </tr>
        <tr>
            <td>AWS</td>
            <td>S3</td>
            <td><a href="https://aws.amazon.com/s3/pricing/">It's complicated</a></td>
            <td>Transfer: ~150 GB monthly = $5</td>
            <td align="right">$60</td>
            <td><small>File storage and transfer. Cost estimated based upon past usage.</small></td>
        </tr>
        <tr>
            <td>AWS</td>
            <td>EKS</td>
            <td>Hourly</td>
            <td>$0.10/hr = ~$74/month</td>
            <td align="right">$888</td>
            <td><small>Kubernetes Cluster management. Shared resource.</small></td>
        </tr>
        <tr>
            <td>AWS</td>
            <td>RDS</td>
            <td>3 Year</td>
            <td>$224</td>
            <td align="right">$74.67</td>
            <td><small>Managed database service; three year reservation for instance.</small></td>
        </tr>
        <tr>
            <td>AWS</td>
            <td>EC2</td>
            <td>3 Year</td>
            <td>$822</td>
            <td align="right">$274.00</td>
            <td><small>Compute power for cluster. Shared resource.</small></td>
        </tr>
        <tr>
            <td colspan="4" align="right"><em>Total</em></td>
            <td align="right">$1320.67</td>
            <td><small>Annually, with 3 year reservations</small></td>
        </tr>
    </tbody>
</table>

<p>The costs on the table above are a snapshot in time. The cost of compute resources is variable. This page will be updated whenever new reservations are purchased to reflect a reasonably current price; or whenever I notice a problem in the accounting.</p>
{% endblock %}

src/donation/templates/donate.html
{% extends "site_base.html" %}

{% block head_title %}Support this site!{% endblock %}


{% block scripts %}
  {% include "_scripts.html" %}
{% endblock %}

{% block content %}
<h1>Thank you!</h1>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
  <div class="paypal-donations">
    <ul>
      <li>Tell me why you're donating today (optional): <textarea id="donation-comment" name="comment"></textarea></li>
      <li>Would you prefer this donation remain private? <input id="donation-private" type="checkbox" name="private" /></li>
    </ul>
    <p><small>Donation notes are moderated for content and may be redacted or not be displayed at the moderator's discretion. No refunds will be provided based upon content moderation choices.</small></p>
    <input type="hidden" name="cmd" value="_donations" />
    <input type="hidden" name="business" value="paul@thismatters.net" />
    <input type="hidden" name="notify_url" value="{{ BASE_URL }}{% url 'paypal-ipn' %}" />
    <input type="hidden" name="return" value="{{ BASE_URL }}{% url 'donations:complete' %}" />
    <input type="hidden" name="cancel_return" value="{{ BASE_URL }}{% url 'donations:cancel' %}" />
    <input type="hidden" name="rm" value="0" />
    <input type="hidden" name="currency_code" value="USD" />
    <input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donate_LG.gif" name="submit" alt="PayPal - The safer, easier way to pay online." />
    <img alt="" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
  </div>
</form>

{% if donations %}
  <h2>Thank you to my supporters!</h2>
  <div class="donations-recieved">
    {% for donation in donations %}
      <div class="donation-recieved">
        <h3>{{ donation.created|date:"M Y"}}&mdash;{% if donation.private %}Anonymous{% else %}{{ donation.user }}{% endif %} gives {{ donation.amount }} and says:</h3>
        <p>{{ donation.moderated_comment }}</p>
      </div>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}


{% block page_scripts %}
<script>
$( "form" ).submit(function(event) {
  {% include "_csrftoken.html" %}
  var post_data = {
    "comment": $("#donation-comment").val(),
    "private": $("#donation-private").is(":checked")
  };
  // post the donation comment to the the endpoint
  $.ajax({
    type: "POST",
    url: "{% url 'donations-api:donation-list' %}",
    data: post_data,
    beforeSend: function(request) {request.setRequestHeader('X-CSRFToken', csrftoken);},
    // retrieve the pk from the created donation record it in the name="custom" input
    success: function(data) {
      var custom_input = '<input type="hidden" name="custom" value="'+data.pk+'" />';
      $('form').append(custom_input);
    },
    async: false
  })
  // post the paypal form
});
</script>

{% endblock %}

src/donation/templates/donate_cancel.html
{% extends "site_base.html" %}

{% block content %}
<h1>Aw sheesh</h1>

<p>I feel like Charlie Brown trying to kick a football right now.</p>

{% endblock %}

src/donation/templates/donate_complete.html
{% extends "site_base.html" %}

{% block content %}
<h1>No, You're the best!</h1>

<p>Thank you for contributing! Payment processing is fast but not immediate, it may take a few moments for your donation to appear in the thermometer.</p>

{% endblock %}