src/account/urls.py
from django.urls import path

from account import views

app_name = "account"

urlpatterns = [
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
]

src/donation/urls.py
from django.urls import path
from django.views.generic import TemplateView

from donation.views import DonationView

app_name = "donations"

urlpatterns = [
    path(
        "boo/", TemplateView.as_view(template_name="donate_cancel.html"), name="cancel"
    ),
    path(
        "thanks/",
        TemplateView.as_view(template_name="donate_complete.html"),
        name="complete",
    ),
    path("start/", DonationView.as_view(), name="start"),
    path("cost/", TemplateView.as_view(template_name="cost.html"), name="cost"),
]

src/solution/urls.py
from django.urls import path

from solution import views

app_name = "solutions"

urlpatterns = [
    # all textbook (versions)
    path("textbooks/", views.TextbookView.as_view(), name="textbooks"),
    # all problems in textbook
    path(
        "textbooks/<slug:textbook_edition_slug>/",
        views.ProblemIndexView.as_view(),
        name="problem_index",
    ),
    # specific problem
    path(
        "textbooks/<slug:textbook_edition_slug>/<int:chapter_number>-<int:problem_number>/",
        views.ProblemView.as_view(),
        name="problem",
    ),
    path("concepts/", views.ConceptIndexView.as_view(), name="concepts"),
    path("concepts/<slug:concept_slug>/", views.ConceptView.as_view(), name="concept"),
    path("streams/", views.StreamIndexView.as_view(), name="streams"),
    path(
        "streams/course/<slug:course_slug>/",
        views.StreamByCourseView.as_view(),
        name="course_streams",
    ),
    path("streams/<slug:stream_slug>/", views.StreamView.as_view(), name="stream"),
    path("<slug:solution_slug>/", views.SolutionView.as_view(), name="solution"),
]

src/tutor_paul/api/urls.py
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="TutorPaul API",
        default_version="v1",
        # terms_of_service='https://www.google.com/policies/terms/',
        # contact=openapi.Contact(email='contact@snippets.local'),
        # license=openapi.License(name='BSD License'),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(
        r"swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "docs/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("solutions/", include("solution.api.urls", namespace="solutions-api")),
    path("donations/", include("donation.api.urls", namespace="donations-api")),
]

src/tutor_paul/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from tutor_paul.views import ContactView, StaticFileView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("auth/", include("social_django.urls", namespace="social")),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
    path("donations/", include("donation.urls", namespace="donations")),
    path("solutions/", include("solution.urls", namespace="solutions")),
    path("contact/", ContactView.as_view(), name="contact"),
    path("api/v1/", include("tutor_paul.api.urls")),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("mailinglist/", include("mailinglist.urls", namespace="mailinglist")),
    path(
        "about/tutorpaul/",
        TemplateView.as_view(template_name="about_tutorpaul.html"),
        name="about_me",
    ),
    path(
        "robots.txt",
        StaticFileView.as_view(static_file="robots.txt"),
        name="robots_txt",
    ),
]

src/tutor_paul/views.py
from django import forms
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage
from django.http import FileResponse
from django.urls import reverse
from django.views import View
from django.views.generic import FormView


class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True, min_length=8)
    message = forms.CharField(widget=forms.Textarea(), required=True, min_length=25)


class ContactView(FormView):
    form_class = ContactForm
    template_name = "contact.html"

    def get_success_url(self):
        return reverse("home")

    def get_initial(self):
        initial = {}
        user = self.request.user
        if not user.is_anonymous:
            initial.update(
                {
                    "email": user.email,
                }
            )
        return initial

    def form_valid(self, form):
        # send the email to me!
        # no worker, send it within the request-response loop
        email = EmailMessage(
            subject="[site-contact] {}".format(form.data["subject"]),
            body=form.data["message"],
            from_email=settings.CONTACT_SENDER,
            to=(settings.CONTACT_EMAIL,),
            reply_to=(form.data["email"],),
        )
        email.send()
        messages.success(self.request, "Email sent")
        return super().form_valid(form)


class StaticFileView(View):
    static_file = "robots.txt"

    def get(self, request, *args, **kwargs):
        return FileResponse(
            open(f"tutor_paul/static/{self.static_file}", "rb"),
            filename=self.static_file.rsplit("/", maxsplit=1).pop(),
        )

src/tutor_paul/templates/_csrftoken.html
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

src/tutor_paul/templates/_header.html
<div class="pan-layout-header__content">
  <div class="pan-layout-header__menutoggle">
    <i class="fas fa-bars"></i>
  </div>
  <div class="pan-layout-header__donations">
    <div class="thermometer">
      <div class="fill" style="width: {{ campaign_percent_complete }}%"></div>
      <span><a href="{% url 'donations:start' %}">Please Donate!</a></span>
    </div>
  </div>
  <div class="pan-layout-header__avatar">
    {% if request.user.is_authenticated %}
      <span><a class="button" href="{% url 'account:profile' %}"><i class="fas fa-user"></i> {{ request.user }}</a></span>
      <span><a class="logout button" href="{% url 'account:logout' %}">Log out</a></span>
    {% else %}
      <span><a class="login button" href="{{ LOGIN_URL }}">Log in</a></span>
    {% endif %}
  </div>
</div>

src/tutor_paul/templates/_license.html
{% load static %}
<span prefix="dct: http://purl.org/dc/terms/ cc: http://creativecommons.org/ns#" class="cc-block"> <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><i class="fab fa-creative-commons"></i></a> <a href="{{ BASE_URL }}{{ request.get_full_path }}" title="Permalink to {{ element.name | title }}"><link href="http://purl.org/dc/dcmitype/Text" rel="dct:type" property="dct:type" /><span property="dct:title">{{ element.name }}</span></a> by <a href="{% url 'about_me' %}" property="cc:attributionName" rel="cc:attributionURL"> Paul</a> is licensed under a <a rel="license" target="_blank" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</span>

src/tutor_paul/templates/_messages.html
{% if messages %}
  <div class="messages">
    <div class="messages-proper">
      <ul>
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    </div>
    <div id="messages-dismiss" class="messages-dismiss">
      <i class="fa fa-window-close" aria-hidden="true"></i>
    </div>
  </div>
{% endif %}

src/tutor_paul/templates/_scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery-migrate-3.0.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'panthera-jekyll.js' %}"></script>
<script type="text/javascript">
$("#messages-dismiss").click(function(e) {
  // dismiss the messages
  $(".messages").css("display", "none")
});
</script>

src/tutor_paul/templates/_styles.html
{% load sass_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'fontawesome-5.9.0/css/all.min.css' %}" type="text/css" />
{% if 1 == 0 %}
    <link href="{% sass_src '_sass/panthera-jekyll.scss' %}" rel="stylesheet" type="text/css" />
{% else %}
    <link href="{% static '_sass/panthera-jekyll.css' %}" rel="stylesheet" type="text/css" />
{% endif %}

src/tutor_paul/templates/about_tutorpaul.html
{% extends "site_base.html" %}
{% load static %}
{% block content %}
    <img src="{% static 'tutorpaul_headshot.jpeg' %}" alt="my pretty mug" />
    <p>Howdy, I'm Paul! I am a former student of Texas A&amp;M, classes of 2005 and 2009! I was fortunate to be selected as a Teachers Assistant for MEEN 363 as a first year graduate student; I held that position 4 semesters eventually working for 3 professors and working with hundreds of dynamics students. During that time I was able to do what I was never able to do as an undergraduate&mdash;master dynamics and vibrations!</p>
    <p>After completing my time as a TA I picked up tutoring for 363 and 364 as a means to supplement my income as a research assistant, and after graduating I transitioned to tutoring as my full time hustle. My students supported me financially for nearly a decade while affording me a tremendous amount of freedom to pursue other interests. Leaving that freedom and support was a very difficult choice for me.</p>
    <p>When I finally did leave A&amp;M and College Station I wanted to leave something behind in recognition of my time there and of the students who helped me to refine the techniques needed to understand dynamics; this site and the content within are my meditation in gratitude and my gift to future Aggie Engineers! I hope that it can inspire you to carry forward a spirit of gratitude for those who came before you and those who paved the path that led you where you are.</p>
    <p>Cheers!</p>
{% endblock %}

src/tutor_paul/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <!--
__/\\\\\\\\\\\\\\\__________________________________________________________/\\\\\\\\\\\\\_________________________________/\\\\\\____
 _\///////\\\/////__________________________________________________________\/\\\/////////\\\______________________________\////\\\____
  _______\/\\\_________________________/\\\__________________________________\/\\\_______\/\\\_________________________________\/\\\____
   _______\/\\\________/\\\____/\\\__/\\\\\\\\\\\_____/\\\\\_____/\\/\\\\\\\__\/\\\\\\\\\\\\\/___/\\\\\\\\\_____/\\\____/\\\____\/\\\____
    _______\/\\\_______\/\\\___\/\\\_\////\\\////____/\\\///\\\__\/\\\/////\\\_\/\\\/////////____\////////\\\___\/\\\___\/\\\____\/\\\____
     _______\/\\\_______\/\\\___\/\\\____\/\\\_______/\\\__\//\\\_\/\\\___\///__\/\\\_______________/\\\\\\\\\\__\/\\\___\/\\\____\/\\\____
      _______\/\\\_______\/\\\___\/\\\____\/\\\_/\\__\//\\\__/\\\__\/\\\_________\/\\\______________/\\\/////\\\__\/\\\___\/\\\____\/\\\____
       _______\/\\\_______\//\\\\\\\\\_____\//\\\\\____\///\\\\\/___\/\\\_________\/\\\_____________\//\\\\\\\\/\\_\//\\\\\\\\\___/\\\\\\\\\_
        _______\///_________\/////////_______\/////_______\/////_____\///__________\///_______________\////////\//___\/////////___\/////////__
    -->

    <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }} | {% endif %}{% block head_title %}{% endblock %}{% endblock %}</title>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% block styles %}
      {% block page_styles %}{% endblock %}
      {% include "_styles.html" %}
    {% endblock %}
    {% block scripts %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block entire_body %}
      {% block notification %}{% include "_messages.html" %}{% endblock %}
      <section class="pan-layout">
        <section class="pan-layout-left">
          {% block sidebar %}
            <div class="pan-layout-left__top">
              <div class="pan-layout-left__info">
                <h1 class="pan-layout-left__title">{{ SITE_NAME }}</h1>
                <h3 class="pan-layout-left__subtitle">Dynamics and Vibrations Solutions</h3>
              </div>
            </div>
            <div class="pan-layout-left__middle">
              {# make template tags for displaying concepts, similar, and next problems #}
              {% block sidebar_main %}
                <div>
                  <h2>MEEN 363</h2>
                  <ul>
                    <li><a class="view-list" href="{% url 'solutions:problem_index' 'childs-11' %}">Textbook Solutions</a></li>
                    <li><a class="view-list" href="{% url 'solutions:concepts' %}">Concepts</a></li>
                    <li><a class="view-list" href="{% url 'solutions:course_streams' 'meen363' %}">Past Streams</a></li>
                  </ul>
                </div>
                <div>
                  <h2>MEEN 364</h2>
                  <ul>
                    <li><a class="view-list" href="{% static 'TutorPaul-MEEN364_Notes-12.pdf' %}" download>Download 364 Notes</a></li>
                    <li><a class="view-list" href="{% url 'solutions:course_streams' 'meen364' %}">Past Streams</a></li>
                  </ul>
                </div>
                <div>
                  <h2>MEEN 368</h2>
                  <ul>
                    <li><a class="view-list" href="{% url 'solutions:course_streams' 'meen368' %}">Past Streams</a></li>
                  </ul>
                </div>
              {% endblock %}
            </div>
            <div class="pan-layout-left__bottom">
              <div class="pan-layout-left__small">
                <span>GET IN TOUCH</span>
              </div>
              <div class="pan-layout-left__social">
                <ul>
                  <li><a target="_blank" href="https://www.twitch.tv/tutorpaul"><i class="fab fa-twitch"></i></a></li>
                  <li><a target="_blank" href="{{ DISCORD_LINK }}"><i class="fab fa-discord"></i></a></li>
                  <li><a target="_blank" href="https://github.com/thismatters"><i class="fab fa-github-square"></i></a></li>
                  <li><a target="_blank" href="https://www.linkedin.com/in/paul-stiverson-4a505a60/"><i class="fab fa-linkedin"></i></a></li>
                  <li><a href="{% url 'contact' %}"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
            <div class="pan-layout-left__close">
              <i class="fa fa-fw fa-times"></i>
            </div>
          {% endblock %}
        </section>
        <section class="pan-layout-overlay"></section>
        <section class="pan-layout-right">
          {% block main %}
            <section class="pan-layout-header">
              {% block header %}
                {% include "_header.html" %}
              {% endblock %}
            </section>
            <section class="pan-layout-content">
              {% block content %}
                <h1>This video and stuff</h1>
                <div>
                  video
                </div>
                <p>stuff</p>
                <p>comments</p>
              {% endblock %}
            </section>
            <section class="pan-layout-footer">
              {% block footer %}
                <div class="pan-layout-footer__content">
                  <div class="left">
                    {% block license %}
                    {% endblock %}
                  </div>
                  <div class="right">
                    <span>Theme adapted from <a target="_blank" href="https://github.com/christianezeani/panthera-jekyll">Panthera-Jekyll</a>.</span>
                  </div>
                </div>
              {% endblock %}
            </section>
          {% endblock %}
        </section>
      </section>
    {% endblock %}
    {% include "_scripts.html" %}
    {% block page_scripts %}{% endblock %}
  </body>
</html>

src/tutor_paul/templates/comment_base.html
{% extends "base.html" %}
{% load static %}

{% block page_styles %}
  <style type="text/css">
    .comment{
      padding-left: 2px;
      border-left: 2px solid black;
     }
    .comment.reply{
      margin-bottom: 0px;
      padding-bottom: 5px;
      padding-top: 0px;
      margin-top: 0px;
    }
  </style>
{% endblock %}

{% block additional_sections %}
  <section class="comments">
    <h2>Comments</h2>
    <div>
      <textarea name="comment" id="reply-to-{{ element_type }}-{{ element.pk }}" class="initial-value">Enter your comment here!</textarea>
      <button class="comment-preview" id="preview-reply-to-{{ element_type }}-{{ element.pk }}">Preview</button><button class="comment-submit" id="submit-reply-to-{{ element_type }}-{{ element.pk }}">Submit</button>
      <div name="preview-comment" id="reply-preview-to-{{ element_type }}-{{ element.pk }}"></div>
    </div>
    <div id="existing-comments">
    </div>
  </section>
  <div style="display: none;">
  </div>
{% endblock %}

{% block license %}
  {% include "_license.html" %}
{% endblock %}

{% block scripts %}
  <script src="{% static 'polyfill.min.js' %}"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  <script src="{% static 'marked.min.js' %}"></script>
{% endblock %}

{% block page_scripts %}
  <script type="text/javascript">
    // process comments here
    function insert_comment(comment_data, parent_element, do_mathjax) {
      var raw = comment_data.comment;
      var preprocessed = raw.replace(/\\([\(\[\)\]])/g, '\\\\$1');
      var comment = marked(preprocessed);
      var new_comment = '<div class="comment" id="comment-'+comment_data.pk+'"><p>'+comment+'</p>By <span class="author">'+comment_data.user_name+'</span> at <span class="created">'+comment_data.created+'</span> &mdash; <span class="reply-button">Reply</span><div class="replies"></div></div>';
      parent_element.append(new_comment);
      for (let reply of comment_data.replies) {
        insert_comment(reply, $(parent_element).find("div#comment-"+comment_data.pk+" > .replies"), false);
      }
      if (do_mathjax) {
        MathJax.typeset();
      }
    };

    // load comments for this page
    window.onload = function() {
      $.ajax({
        type: "GET",
        url: "{% url 'solutions-api:comment-list' %}?{{ element_type }}_pk={{ element.pk }}",
        success: function(data) {
          // paint them into div named "existing-comments"
          var receiver = $("#existing-comments");
          receiver.empty();
          for (let comment of data) {
            insert_comment(comment, receiver, false);
          }
          MathJax.typeset();
        }
      })
    };

    // Bring the reply box
    $("body").on("click", "span.reply-button", function() {
      // disable the reply button
      $(this).toggleClass("reply-button unreply-button");
      $(this).html('Unreply');
      // make the empty form
      var parent_id = $(this).parent().attr("id");
      var reply_box = '<div class="write-reply" id="reply-div-'+parent_id+'"><textarea id="reply-to-'+parent_id+'"></textarea><button class="comment-preview" id="preview-reply-to-'+parent_id+'">Preview</button><button class="comment-submit" id="submit-reply-to-'+parent_id+'">Submit</button><div name="preview-comment" id="reply-preview-to-'+parent_id+'"></div></div>';

      // insert it into the dom under the correct element
      $(reply_box).insertAfter($(this));
      // put cursor into the textarea
    });

    // Disappear the the reply box
    $("body").on("click", "span.unreply-button", function() {
      // re-activate the reply button
      $(this).toggleClass("reply-button unreply-button");
      $(this).html('Reply');
      // remove the reply box
      $(this).parent().find("div.write-reply").remove();
    });

    // Submit a comment/reply
    $("body").on("click", "button.comment-submit", function() {
      {% include "_csrftoken.html" %}
      // get the id of the thing to be replied to (comment or page object)
      var textarea_id = $(this).attr("id").replace(/submit-/, "");
      var replying_to = textarea_id.replace(/reply-to-/, "").split("-");
      var comment_types = {
        "comment": "in_response_to_pk",
        "concept": "concept_pk",
        "solution": "solution_pk"
      }

      var comment = $("textarea#" + textarea_id).val().trim();
      var post_data = {"comment": comment};
      post_data[comment_types[replying_to[0]]] = replying_to[1];

      // send the comment in
      $.ajax({
        type: "POST",
        url: "{% url 'solutions-api:comment-list' %}",
        data: post_data,
        beforeSend: function(request) {request.setRequestHeader('X-CSRFToken', csrftoken);},
        success: function (data) {
          // paint the created comment onto the screen
          if (replying_to[0] == 'comment') {
            var reply_button = $("div#comment-"+data.in_response_to_pk+" > .unreply-button");
            // restore the reply button
            reply_button.toggleClass("reply-button unreply-button");
            reply_button.html('Reply');
            var recipient = $("div#comment-"+data.in_response_to_pk+" > .replies");
            // remove the reply box
            $("div#reply-div-comment-" + data.in_response_to_pk).remove();
          } else {
            var recipient = $("#existing-comments");
            $("textarea#" + textarea_id).val("");
          }
          insert_comment(data, recipient, true);
        }
      });
    });

    // preview a comment/reply
    $("body").on("click", "button.comment-preview", function() {
      var textarea_id = $(this).attr("id").replace(/preview-/, "");
      var replying_to = textarea_id.replace(/reply-to-/, "").split("-");

      var raw = $("textarea#" + textarea_id).val().trim();
      var preprocessed = raw.replace(/\\([\(\[\)\]])/g, '\\\\$1');
      var comment = marked(preprocessed);
      $("#reply-preview-to-" + replying_to.join("-")).html(comment);
      MathJax.typeset();
    });

    // remove the starter text from the page comment box
    $("body").on("focus", ".initial-value", function() {
      $(this).val("");
      $(this).toggleClass("initial-value", false);
    });
  </script>
{% endblock %}

src/tutor_paul/templates/contact.html
{% extends "site_base.html" %}

{% block head_title %}Contact{% endblock %}

{% block content %}
  <h1>Howdy!</h1>
  <p>You know the drill: fill in the details hit send. If you are interested in contributing to this site, or have a bug to report then please direct communication through the <a href="https://gitlab.com/tutorpaul/tutor-paul">Gitlab repo</a>. Please note, I'm not looking for <b>any</b> professional services related to this site, a cold-email from you isn't going to change that.</p>

  <form method="POST" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
  </form>

{% endblock %}

src/tutor_paul/templates/home.html
{% extends "site_base.html" %}

{% block head_title %}Welcome{% endblock %}

{% block content %}
  <h1>Howdy!</h1>
  <p>I hope you came here for some rootin-tootin dynamics and vibrations help, because that is 99.9% of what you'll find here. The remainder is my wit.</p>

  <p><a href="{% url 'solutions:textbooks' %}">Jump in by choosing your textbook (after logging in with a google account).</a> I haven't been able to cross-reference all the problems from the 10th edition to the 11th, so if you can't find a solution for a problem in the 11th edition, look for it in the 10th edition and leave a comment to indicate which problem it is the 11th edition!</p>

  <p>Or, if you're here to make a donation <a href="{% url 'donations:start' %}">then I'll leave you to it</a></p>

  <p>I hope you find this useful.</p>

  <h2>Twitch Stream</h2>

  <p>I had a lot of fun streaming homework help sessions and exam reviews last semester and I want to keep it going and expand! I want to continue a weekly stream for MEEN 364, and I want to start doing a periodic exam review stream for MEEN 363. <a href="https://www.twitch.tv/tutorpaul">Follow me (and sub!)</a> for my streams! <a href="{{ DISCORD_LINK }}">Join my discord</a> to suggest streams and help me stay current with your course.</p>

  <h2>About this site</h2>

  <p>This site is an active gift to all Mechanical Engineering students at Texas A&amp;M! I promise the content within is 100% ad-free and offered without fee. The google account you sign up with will be emailed a maximum of 1 time per year (though most likely never). I sell no data pertaining to this site whatsoever.</p>

  <p>I only ask that you <a href="{% url 'donations:start' %}">contribute</a>&mdash;if possible&mdash;to cover the operational expenses of the site. All said <a href="{% url 'donations:cost' %}">this site costs a little over $1300 per year</a>, the thermometer at the top of the page shows how close we are to meeting the $650 per semester goal.</p>

  <p>This is an <a href="https://gitlab.com/tutorpaul/tutor-paul">open source project</a> and contributions are welcome!</p>

  <p>If you find an error or omission in any content feel free to leave a comment. The comments support Mathjax so <a href="https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference">you can type math more beautifully</a>.</p>

{% endblock %}

src/tutor_paul/templates/logout.html
{% extends "site_base.html" %}

{% block head_title %}Logout{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'account:logout' %}">
        <legend>Log out</legend>
        <div>
            {% csrf_token %}
            <p>You are logged in as {{ request.user.email }}. Are you sure you want to log out?</p>
            <p>If you are having a hard time signing in to the correct account try a private tab.</p>
            <button type="submit" class="red" name="logout-confirm">Log out</button>
        </div>
    </form>
{% endblock %}

src/tutor_paul/templates/profile.html
{% extends "site_base.html" %}

{% block head_title %}Profile{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

src/tutor_paul/templates/site_base.html
{% extends "base.html" %}