src/account/urls.py
from django.urls import path

from account import views

app_name = "account"

urlpatterns = [
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
]

src/donation/urls.py
from django.urls import path
from django.views.generic import TemplateView

from donation.views import DonationView

app_name = "donations"

urlpatterns = [
    path(
        "boo/", TemplateView.as_view(template_name="donate_cancel.html"), name="cancel"
    ),
    path(
        "thanks/",
        TemplateView.as_view(template_name="donate_complete.html"),
        name="complete",
    ),
    path("start/", DonationView.as_view(), name="start"),
    path("cost/", TemplateView.as_view(template_name="cost.html"), name="cost"),
]

src/solution/api/urls.py
from rest_framework import routers

from solution.api.views import (
    CommentViewSet,
    CourseViewSet,
    StreamSupplementViewSet,
    StreamViewSet,
)

# from django.urls import path


app_name = "solutions-api"

router = routers.SimpleRouter()
router.register(r"comments", CommentViewSet, basename="comment")
router.register(r"courses", CourseViewSet, basename="course")
router.register(r"streams", StreamViewSet, basename="stream")
router.register(
    r"streamSupplements", StreamSupplementViewSet, basename="stream_supplement"
)
urlpatterns = router.urls

src/solution/urls.py
from django.urls import path

from solution import views

app_name = "solutions"

urlpatterns = [
    # all textbook (versions)
    path("textbooks/", views.TextbookView.as_view(), name="textbooks"),
    # all problems in textbook
    path(
        "textbooks/<slug:textbook_edition_slug>/",
        views.ProblemIndexView.as_view(),
        name="problem_index",
    ),
    # specific problem
    path(
        "textbooks/<slug:textbook_edition_slug>/<int:chapter_number>-<int:problem_number>/",
        views.ProblemView.as_view(),
        name="problem",
    ),
    path("concepts/", views.ConceptIndexView.as_view(), name="concepts"),
    path("concepts/<slug:concept_slug>/", views.ConceptView.as_view(), name="concept"),
    path("streams/", views.StreamIndexView.as_view(), name="streams"),
    path(
        "streams/course/<slug:course_slug>/",
        views.StreamByCourseView.as_view(),
        name="course_streams",
    ),
    path("streams/<slug:stream_slug>/", views.StreamView.as_view(), name="stream"),
    path("<slug:solution_slug>/", views.SolutionView.as_view(), name="solution"),
]

src/solution/api/views.py
from django.db.models import Q
from django_filters import rest_framework as filters
from rest_framework.permissions import BasePermission, IsAdminUser
from rest_framework.viewsets import ModelViewSet

from solution.api.serializers import (
    CommentSerializer,
    CourseSerializer,
    StreamSerializer,
    StreamSupplementSerializer,
)
from solution.models import Comment, Course, Stream, StreamSupplement


class CourseViewSet(ModelViewSet):
    model = Course
    serializer_class = CourseSerializer
    lookup_url_kwarg = "course_slug"
    permission_classes = [IsAdminUser]
    queryset = Course.objects.all()
    lookup_field = "slug"


class StreamViewSet(ModelViewSet):
    model = Stream
    serializer_class = StreamSerializer
    lookup_url_kwarg = "stream_pk"
    permission_classes = [IsAdminUser]
    queryset = Stream.objects.all()


class StreamSupplementViewSet(ModelViewSet):
    model = StreamSupplement
    serializer_class = StreamSupplementSerializer
    lookup_url_kwarg = "stream_supplement_pk"
    permission_classes = [IsAdminUser]
    queryset = StreamSupplement.objects.all()


class CommentFilter(filters.FilterSet):
    user = filters.CharFilter(field_name="user", lookup_expr="username")
    user_pk = filters.NumberFilter(field_name="user", lookup_expr="pk")
    solution_slug = filters.CharFilter(field_name="solution", lookup_expr="slug")
    solution_pk = filters.CharFilter(field_name="solution", lookup_expr="pk")
    concept_slug = filters.CharFilter(field_name="concept", lookup_expr="slug")
    concept_pk = filters.CharFilter(field_name="concept", lookup_expr="pk")
    stream_pk = filters.CharFilter(field_name="stream", lookup_expr="pk")
    in_response_to_pk = filters.CharFilter(
        field_name="in_response_to", lookup_expr="pk"
    )

    class Meta:
        model = Comment
        fields = {
            "created": ("gt", "lt"),
        }


class IsOwnerOrAdmin(BasePermission):
    """
    Custom permission to allow access to any User who holds an active
      Household.
    """

    def has_permission(self, request, view):
        return bool(request.user and request.user.is_authenticated)

    def has_object_permission(self, request, view, obj):
        return request.user == obj.user or request.user.is_staff


class CommentViewSet(ModelViewSet):
    """
    Retrieve, create, update or destroy comments.
    """

    model = Comment
    serializer_class = CommentSerializer
    lookup_url_kwarg = "comment_pk"
    filterset_class = CommentFilter
    permission_classes = [IsOwnerOrAdmin]

    def perform_create(self, serializer):
        # print(self.request.user)
        serializer.save(user=self.request.user)

    def get_queryset(self):
        # exclude comments which needs_review and isn't by the requesting user
        # exclude comments which is_rejected and isn't by the requesting user
        user = self.request.user
        return Comment.objects.filter(in_response_to=None).exclude(
            (Q(needs_review=True) | Q(is_rejected=True)) & ~Q(user=user)
        )

src/solution/views.py
from django.contrib import messages
from django.db.models import Prefetch
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.generic import DetailView, ListView, RedirectView

from account.mixins import LoginRequiredMixin
from donation.mixins import DonationRequiredMixin
from solution.models import (
    Announcement,
    Concept,
    Course,
    Problem,
    Solution,
    Stream,
    TextbookEdition,
    TextbookEditionPreference,
)


class AnnouncementMixin:
    course_ident_tokens = ("course",)

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        # get course
        ptr = self.object
        for token in self.course_ident_tokens:
            ptr = getattr(ptr, token)
        announcements = Announcement.objects.filter(
            course=ptr, show_date__lt=timezone.now(), remove_date__gt=timezone.now()
        )
        ctx.update({"announcements": announcements})
        return ctx


class TextbookView(LoginRequiredMixin, ListView):
    template_name = "textbooks.html"
    queryset = TextbookEdition.objects.all().select_related("textbook")

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        # gather all the textbook editions
        object_list = ctx.pop("object_list")
        # reform like {textbook_name: {'textbook': textbook, 'editions':['edition']}, ...}
        prelim_objects = {}
        for _object in object_list:
            # accumulate all the editions by textbook
            _txt = _object.textbook
            _this = prelim_objects.setdefault(
                _txt.slug, {"textbook": _txt, "editions": []}
            )
            _this["editions"].append(_object)
        new_object_list = []
        for _, prelim in prelim_objects.items():
            # drop the textbook slug
            new_object_list.append(prelim)

        ctx.update({"object_list": new_object_list})
        return ctx


class ProblemIndexView(LoginRequiredMixin, ListView):
    template_name = "problems.html"
    slug_url_kwarg = "textbook_edition_slug"
    slug_field = "textbook_edition"

    def dispatch(self, request, *args, **kwargs):
        _selected_edition = self.kwargs.get(self.slug_url_kwarg)
        self.selected_edition = get_object_or_404(
            TextbookEdition, slug=_selected_edition
        )
        self.selected_edition.set_as_preferred_for_user(request.user)

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update(
            {
                "textbook_edition": self.selected_edition,
            }
        )
        return ctx

    def get_queryset(self, *args, **kwargs):
        slug = self.kwargs.get(self.slug_url_kwarg)
        queryset = Problem.objects.filter(textbook_edition__slug=slug)
        return queryset


class ProblemView(LoginRequiredMixin, RedirectView):
    """Redirects to a solution based on the chapter, problem number,
    and textbook edition"""

    def get_redirect_url(self, *args, **kwargs):
        textbook_edition_slug = kwargs.get("textbook_edition_slug")
        chapter_number = kwargs.get("chapter_number")
        problem_number = kwargs.get("problem_number")
        try:
            problem = Problem.objects.get(
                textbook_edition__slug=textbook_edition_slug,
                chapter_number=chapter_number,
                problem_number=problem_number,
            )
        except Problem.DoesNotExist:
            # send them back to the textbook index
            messages.error(
                self.request,
                "Couldn't find problem {}.{} in ".format(chapter_number, problem_number)
                + "{}. Perhaps look for the problem in an ".format(
                    textbook_edition_slug
                )
                + "older edition, if you find it please leave a comment to let me know!",
            )
            print("injecting message")
            url = reverse(
                "solutions:problem_index",
                kwargs={"textbook_edition_slug": textbook_edition_slug},
            )
        else:
            url = reverse(
                "solutions:solution", kwargs={"solution_slug": problem.solution.slug}
            )
        return url


class StreamView(DonationRequiredMixin, AnnouncementMixin, DetailView):
    template_name = "stream.html"
    slug_url_kwarg = "stream_slug"
    slug_field = "slug"
    queryset = Stream.objects.all().prefetch_related("supplements")
    extra_context = {"element_type": "stream"}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({"element": ctx["object"]})
        return ctx


class StreamIndexView(LoginRequiredMixin, ListView):
    template_name = "streams.html"
    queryset = Stream.objects.all()


class StreamByCourseView(LoginRequiredMixin, ListView):
    template_name = "streams.html"
    slug_url_kwarg = "course_slug"
    slug_field = "course"

    def get_queryset(self, *args, **kwargs):
        slug = self.kwargs.get(self.slug_url_kwarg)
        self.course = get_object_or_404(Course, slug=slug)
        queryset = Stream.objects.filter(course=self.course)
        return queryset

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({"course": self.course})
        return ctx


class SolutionView(LoginRequiredMixin, AnnouncementMixin, DetailView):
    template_name = "problem.html"
    slug_url_kwarg = "solution_slug"
    slug_field = "slug"
    queryset = Solution.objects.all().prefetch_related("supplements")
    extra_context = {"element_type": "solution"}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # next problems (based on textbook edition)
        current = ctx["object"]
        user = self.request.user
        edition = TextbookEditionPreference.objects.get(user=user).textbook_edition
        editions = TextbookEdition.objects.filter(textbook=edition.textbook)

        current_problem = Problem.objects.get(
            solution=current, textbook_edition=edition
        )
        prior = (
            Problem.objects.filter(
                chapter_number=current_problem.chapter_number,
                problem_number__lt=current_problem.problem_number,
                textbook_edition=edition,
            )
            .prefetch_related(Prefetch("solution"))
            .order_by("-problem_number")
        )
        following = Problem.objects.filter(
            chapter_number=current_problem.chapter_number,
            problem_number__gt=current_problem.problem_number,
            textbook_edition=edition,
        ).prefetch_related(Prefetch("solution"))
        ctx.update(
            {
                "prior": reversed(prior[:5]),
                "current": current_problem,
                "following": following[:5],
                "editions": editions,
            }
        )
        ctx.update({"element": ctx["object"]})
        return ctx


class ConceptView(LoginRequiredMixin, AnnouncementMixin, DetailView):
    template_name = "concept.html"
    slug_url_kwarg = "concept_slug"
    slug_field = "slug"
    queryset = Concept.objects.all()
    extra_context = {"element_type": "concept"}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({"element": ctx["object"]})
        return ctx


class ConceptIndexView(LoginRequiredMixin, ListView):
    template_name = "concepts.html"
    queryset = Concept.objects.all()

src/solution/templates/_comments.html
<script type="text/javascript">
  // process comments here
  function insert_comment(comment_data, parent_element, do_mathjax) {
    var raw = comment_data.comment;
    var preprocessed = raw.replace(/\\([\(\[\)\]])/g, '\\\\$1');
    var comment = marked(preprocessed);
    var comment_date = new Date(comment_data.created).toLocaleString("en-US");
    // var commentor = comment_data.first_name + " " comment_data.last_name;
    var commentor = comment_data.user_name;
    var awaiting_review = "";
    if (comment_data.needs_review) {
      awaiting_review = '<span class="review">Awaiting Review</span> ';
    }
    var new_comment = '<div class="comment" id="comment-'+comment_data.pk+'"><p>'+comment+'</p>By <span class="author">'+commentor+'</span> at <span class="created">'+comment_date+'</span> '+awaiting_review+'&mdash; <span class="reply-button">Reply</span><div class="replies"></div></div>';
    parent_element.prepend(new_comment);
    for (let reply of comment_data.replies) {
      insert_comment(reply, $(parent_element).find("div#comment-"+comment_data.pk+" > .replies"), false);
    }
    if (do_mathjax) {
      MathJax.typeset();
    }
  };

  // load comments for this page
  window.onload = function() {
    $.ajax({
      type: "GET",
      url: "{% url 'solutions-api:comment-list' %}?{{ element_type }}_pk={{ element.pk }}",
      success: function(data) {
        // paint them into div named "existing-comments"
        var receiver = $("#existing-comments");
        receiver.empty();
        for (let comment of data) {
          insert_comment(comment, receiver, false);
        }
        MathJax.typeset();
      }
    })
  };

  // Bring the reply box
  $("body").on("click", "span.reply-button", function() {
    // disable the reply button
    $(this).toggleClass("reply-button unreply-button");
    $(this).html('Unreply');
    // make the empty form
    var parent_id = $(this).parent().attr("id");
    var reply_box = '<div class="write-comment write-reply" id="reply-div-'+parent_id+'"><div class="comment-proper"><textarea id="reply-to-'+parent_id+'" placeholder="Write your reply!"></textarea></div><div class="comment-control"><div class="preview-comment" name="preview-comment" id="reply-preview-to-'+parent_id+'"></div><button class="comment-preview" id="preview-reply-to-'+parent_id+'">Preview</button><button class="comment-submit" id="submit-reply-to-'+parent_id+'">Submit</button></div></div>';

    // insert it into the dom under the correct element
    $(reply_box).insertAfter($(this));
    // put cursor into the textarea
  });

  // Disappear the the reply box
  $("body").on("click", "span.unreply-button", function() {
    // re-activate the reply button
    $(this).toggleClass("reply-button unreply-button");
    $(this).html('Reply');
    // remove the reply box
    $(this).parent().find("div.write-reply").remove();
  });

  // Submit a comment/reply
  $("body").on("click", "button.comment-submit", function() {
    {% include "_csrftoken.html" %}
    // get the id of the thing to be replied to (comment or page object)
    var textarea_id = $(this).attr("id").replace(/submit-/, "");
    var replying_to = textarea_id.replace(/reply-to-/, "").split("-");
    var comment_types = {
      "comment": "in_response_to_pk",
      "concept": "concept_pk",
      "solution": "solution_pk"
    }

    var comment = $("textarea#" + textarea_id).val().trim();
    var post_data = {"comment": comment};
    post_data[comment_types[replying_to[0]]] = replying_to[1];

    // send the comment in
    $.ajax({
      type: "POST",
      url: "{% url 'solutions-api:comment-list' %}",
      data: post_data,
      beforeSend: function(request) {request.setRequestHeader('X-CSRFToken', csrftoken);},
      success: function (data) {
        // paint the created comment onto the screen
        if (replying_to[0] == 'comment') {
          var reply_button = $("div#comment-"+data.in_response_to_pk+" > .unreply-button");
          // restore the reply button
          reply_button.toggleClass("reply-button unreply-button");
          reply_button.html('Reply');
          var recipient = $("div#comment-"+data.in_response_to_pk+" > .replies");
          // remove the reply box
          $("div#reply-div-comment-" + data.in_response_to_pk).remove();
        } else {
          var recipient = $("#existing-comments");
          $("textarea#" + textarea_id).val("");
        }
        insert_comment(data, recipient, true);
      }
    });
  });

  // preview a comment/reply
  $("body").on("click", "button.comment-preview", function() {
    var textarea_id = $(this).attr("id").replace(/preview-/, "");
    var replying_to = textarea_id.replace(/reply-to-/, "").split("-");

    var raw = $("textarea#" + textarea_id).val().trim();
    var preprocessed = raw.replace(/\\([\(\[\)\]])/g, '\\\\$1');

    var preview_element = $("#reply-preview-to-" + replying_to.join("-"));
    var comment = marked(preprocessed);
    preview_element.html(comment);
    preview_element.css("display", "block");
    MathJax.typeset();
  });

  // remove the starter text from the page comment box
  $("body").on("focus", ".initial-value", function() {
    $(this).val("");
    $(this).toggleClass("initial-value", false);
  });
</script>

src/solution/templates/_video_controls.html
<script type="text/javascript">
  function resizeVideo(width, height) {
    var video = $("#video-proper")[0];
    video.width = width;
    video.height = height;
    // video.setAttribute('width ', width);
  }
  $("#video-control-small").click(function (e) {
    // w=472 h=270
    resizeVideo(472, 270);
  });
  $("#video-control-medium").click(function (e) {
    // w=708 h=405
    resizeVideo(708, 405);
  });
  $("#video-control-large").click(function (e) {
    // w=944 h=540
    resizeVideo(944, 540);
  });

  function setPlaybackRate(rate) {
    var video = $("#video-proper")[0];
    video.playbackRate = rate;
  }
  $("#video-control-slow").click(function (e) {
    setPlaybackRate(0.66);
  });
  $("#video-control-regular").click(function (e) {
    setPlaybackRate(1);
  });
  $("#video-control-fast").click(function (e) {
    setPlaybackRate(1.5);
  });
  $("#video-control-omg").click(function (e) {
    setPlaybackRate(3);
  });
</script>

src/solution/templates/comment_action.html
{% extends "admin/base_site.html" %}

{% block content %}
    <h1>Comment has been {{ action }}</h1>
{% endblock %}

src/solution/templates/concept.html
{% extends "video_base.html" %}

{% block head_title %}Concept | {{ object.name }}{% endblock %}

{% block sidebar_main %}
  {{ block.super }}

  <div class="related-problems">
    {% if object.solutions %}
      <h2>Related Problems</h2>
      <ul>
        {% for solution in object.solutions.all %}
          <li><a href="{% url 'solutions:solution' solution_slug=solution.slug %}">{{ solution.name }}</a></li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

src/solution/templates/concepts.html
{% extends "site_base.html" %}

{% block head_title %}Concepts{% endblock %}

{% block content %}
  <ul>
    {% for object in object_list %}
      <li><a href="{% url 'solutions:concept' concept_slug=object.slug %}">{{ object }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

src/solution/templates/problem.html
{% extends "video_base.html" %}
{% load static %}

{% block head_title %}Solution | {{ object.name }}{% endblock %}
{% block body_class %}problem{% endblock %}

{% block subtitle %}<span>a.k.a {{ current.textbook_edition }} problem {{ current.chapter_number }}.{{ current.problem_number }}</span>{% endblock %}

{% block sidebar_main %}
  <div class="noteset">
    <h2>Noteset</h2>
    <a href="{% static 'TutorPaul-MEEN364_Notes-12.pdf' %}" download>Download 364 Notes</a>
  </div>
  <div class="related-concepts">
    {% if object.concepts %}
      <h2>Related Concepts</h2>
      <a class="view-list" href="{% url 'solutions:concepts' %}">See all</a>
      <ul>
        {% for concept in object.concepts.all %}
          <li><a href="{% url 'solutions:concept' concept_slug=concept.slug %}">{{ concept.name }}</a></li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
  <div class="proximate-problems">
    <h2>Other Problems</h2>
    <a class="view-list" href="{% url 'solutions:problem_index' textbook_edition_slug=current.textbook_edition.slug %}">See all</a>
    <ul>
      {% if prior %}
        {% for prob in prior %}
          <li><a href="{% url 'solutions:solution' solution_slug=prob.solution.slug %}">{{ prob.chapter_number }}.{{ prob.problem_number }}</a></li>
        {% endfor %}
      {% endif %}
      <li>{{ current.chapter_number }}.{{ current.problem_number }}</li>
      {% if following %}
        {% for prob in following %}
          <li><a href="{% url 'solutions:solution' solution_slug=prob.solution.slug %}">{{ prob.chapter_number }}.{{ prob.problem_number }}</a></li>
        {% endfor %}
      {% endif %}
    </ul>
  </div>
{% endblock %}

{% block supplements %}
  <div class="supplements">
    {% if object.supplements.all %}
      <h2>Supplement{% if object.supplements.all|length > 1 %}s{% endif %}</h2>
      <div class="supplement-picker">
        <ul id="supplement-picker">
        {% if object.supplements.all|length > 1 %}
          {% for supplement in object.supplements.all %}
              <li id="{{ supplement.url }}"><a href="#">{{ supplement.name | title }}</a></li>
          {% endfor %}
        {% endif %}
        </ul>
      </div>
      <div class="worksheet" id="supplement-viewer">
        <img src="{{ object.supplements.all.0.url }}">
      </div>
    {% endif %}
  </div>
{% endblock %}


{% block page_scripts %}
  {{ block.super }}
  <script type="text/javascript">
    $("#supplement-picker li").click(function(event) {
      // put the image in the supplment-viewer
      $("#supplement-viewer img").attr("src", $(this).attr("id"));
      // make others unselected
      $("#supplement-picker li").each(function() {
        $(this).toggleClass("selected", false);
      });
      // make $(this) selected
      $(this).toggleClass("selected", true)
    });
  </script>
{% endblock %}

src/solution/templates/problems.html
{% extends "site_base.html" %}

{% block head_title %}Solutions{% endblock %}

{% block content %}
  <p><b>{{ textbook_edition }}</b></p>
  <ul>
    {% for object in object_list %}
      <li><a href="{% url 'solutions:solution' solution_slug=object.solution.slug %}">{{ object.chapter_number }}.{{ object.problem_number }}{% if object.method %} ({{ object.method }}){% endif %}</li>
    {% endfor %}
  </ul>
{% endblock %}

src/solution/templates/stream.html
{% extends "video_base.html" %}
{% load static %}

{% block head_title %}Stream | {{ object.name }}{% endblock %}
{% block body_class %}stream{% endblock %}

{% block subtitle %}<span>{{ current.name }}</span>{% endblock %}

{% block supplements %}
  <div class="supplements">
    {% if object.supplements.all %}
      <h2>Supplement{% if object.supplements.all|length > 1 %}s{% endif %}</h2>
      <div class="supplement-picker">
        <ul id="supplement-picker">
        {% if object.supplements.all|length > 1 %}
          {% for supplement in object.supplements.all %}
              <li id="{{ supplement.url }}"><a href="#">{{ supplement.name | title }}</a></li>
          {% endfor %}
        {% endif %}
        </ul>
      </div>
      <div class="worksheet" id="supplement-viewer">
        <img src="{{ object.supplements.all.0.url }}">
      </div>
    {% endif %}
  </div>
{% endblock %}


{% block page_scripts %}
  {{ block.super }}
  <script type="text/javascript">
    $("#supplement-picker li").click(function(event) {
      // put the image in the supplment-viewer
      $("#supplement-viewer img").attr("src", $(this).attr("id"));
      // make others unselected
      $("#supplement-picker li").each(function() {
        $(this).toggleClass("selected", false);
      });
      // make $(this) selected
      $(this).toggleClass("selected", true)
    });
  </script>
{% endblock %}

src/solution/templates/streams.html
{% extends "site_base.html" %}

{% block head_title %}Streams{% endblock %}

{% block content %}
  <p>Streams remain on Twitch for 14 days, where they can be viewed without restriction. Before they expire from Twitch streams will be archived here.</p>
  <p>Note that only people who have <a href="{% url 'donations:start' %}">donated at least $15</a> have access to past streams (anonymous donations still count!).</p>
  <ul>
    {% for object in object_list %}
      <li><a href="{% url 'solutions:stream' stream_slug=object.slug %}">{{ object.name }} &mdash; {{ object.created|date:"d M, Y" }}</li>
    {% empty %}
      <li>No streams yet for {{ course }}. Go to <a href="{{ DISCORD_LINK }}">the discord and make a request!</a></li>
    {% endfor %}
  </ul>
{% endblock %}

src/solution/templates/textbooks.html
{% extends "site_base.html" %}

{% block head_title %}Textbooks{% endblock %}

{% block content %}
  <ul>
    {% for object in object_list %}
      <li>{{ object.textbook.name }} &mdash; {{ object.textbook.author }}
        <ul>
          {% for edition in object.editions %}
            <li><a href="{% url 'solutions:problem_index' textbook_edition_slug=edition.slug %}">{{ edition.edition }} Edition</a></li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

src/solution/templates/video_base.html
{% extends "base.html" %}
{% load static %}

{% block page_styles %}
  <style type="text/css">
    .announcements {
      border: #000000 solid 1px;
      padding: 10px;
      background: #93F4A7;
      border-radius: 4px;
      display: block;
    }
  </style>
{% endblock %}

{% block content %}
  {% block announcements %}
    {% if announcements %}
      <div class="announcements">
        {% for announcement in announcements %}
          <span>{{ announcement.text|safe }}</span>
        {% endfor %}
      </div>
    {% endif %}
  {% endblock %}

  <h1>{{ element.name }}</h1>
  {% block subtitle %}
  {% endblock %}
  <div class="video">
    <video id="video-proper" width="472" height="270" poster="{{ element.opening_card_url }}" controls="controls" preload="none">
      <source src="{{ element.video_url }}" type="video/mp4" />
    </video>
    <div class="video-controls">
      <ul>
        <li><a id="video-control-small" href="#">small</a></li>
        <li><a id="video-control-medium" href="#">medium</a></li>
        <li><a id="video-control-large" href="#">large</a></li>
        <li><a id="video-control-slow" href="#">slow</a></li>
        <li><a id="video-control-regular" href="#">regular</a></li>
        <li><a id="video-control-fast" href="#">fast</a></li>
        <li><a id="video-control-omg" href="#">omg</a></li>
      </ul>
    </div>
  </div>
  {% block supplements %}
  {% endblock %}
  <div class="comments">
    <h2>Comments</h2>
    <div class="write-comment">
      <div class="comment-proper">
        <textarea name="comment" id="reply-to-{{ element_type }}-{{ element.pk }}" class="initial-value" placeholder="Enter your comment here!"></textarea>
      </div>
      <div class="comment-control">
        <div class="preview-comment" name="preview-comment" id="reply-preview-to-{{ element_type }}-{{ element.pk }}"></div>
        <button class="comment-preview" id="preview-reply-to-{{ element_type }}-{{ element.pk }}">Preview</button><button class="comment-submit" id="submit-reply-to-{{ element_type }}-{{ element.pk }}">Submit</button>
      </div>
    </div>
    <div id="existing-comments">
    </div>
  </div>
  <div style="display: none;">
  </div>
{% endblock %}

{% block license %}
  {% include "_license.html" %}
{% endblock %}

{% block scripts %}
  <script src="{% static 'polyfill.min.js' %}"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  <script src="{% static 'marked.min.js' %}"></script>
{% endblock %}

{% block page_scripts %}
  {% include "_comments.html" %}
  {% include "_video_controls.html" %}
{% endblock %}